baseURL = "https://vsxen.github.io/"
title = "Code Life"
copyright = "© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
theme = [ "hugo-PaperMod" ]
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
defaultContentLanguage = "zh"
mainsections = [ "posts", "papermod" ]

[minify]
disableXML = true

[pagination]
disableAliases = false
pagerSize = 5

[languages.zh]
languageName = "Chinese"
weight = 1

  [languages.zh.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.zh.menu.main]]
name = "Archive"
url = "/posts/archives/"
weight = 5



[[languages.zh.menu.main]]
name = "Tags"
url = "tags/"
weight = 10




[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
images = [ "images/papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Code Life"
  Content = """
简单记录
"""



  [params.editPost]
  URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
